apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: williankazuo/service-a
          resources:
            limits:
              memory: "64Mi"
              cpu: "64m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: service-a
